In [8]:
import pandas as pd
import json

In [3]:
df = pd.read_csv("../data.csv")
df

,Experiment Name,Learning Rate,Momentum,Loss
0,fashion_mnist_experiment_10__0.001_0.5,0.001,0.5,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
1,fashion_mnist_experiment_1__0.001_0.9,0.001,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
2,fashion_mnist_experiment_2__0.005_0.9,0.005,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
3,fashion_mnist_experiment_3__0.01_0.9,0.010,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
4,fashion_mnist_experiment_4__0.1_0.9,0.100,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
5,fashion_mnist_experiment_5__1_0.9,1.000,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
6,fashion_mnist_experiment_6__1_0.7,1.000,0.7,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
7,fashion_mnist_experiment_7__0.01_0.7,0.010,0.7,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
8,fashion_mnist_experiment_8__0.001_0.7,0.001,0.7,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."
9,fashion_mnist_experiment_9__0.005_0.5,0.005,0.5,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6..."

In [22]:
def parse_loss(loss):
    loss = json.loads(loss)
    loss_vector = loss['Value']
    return loss_vector

steps = json.loads(df['Loss'][0])['Step']
steps
df['Loss Vector'] = df['Loss'].apply(parse_loss)
df

,Experiment Name,Learning Rate,Momentum,Loss,Loss Vector
0,fashion_mnist_experiment_10__0.001_0.5,0.001,0.5,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[2.2836525440216064, 2.127453565597534, 1.2666..."
1,fashion_mnist_experiment_1__0.001_0.9,0.001,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[1.7812299728393557, 0.8076745867729187, 0.695..."
2,fashion_mnist_experiment_2__0.005_0.9,0.005,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[1.1423888206481934, 0.691998302936554, 0.5947..."
3,fashion_mnist_experiment_3__0.01_0.9,0.010,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[1.151899337768555, 0.8737839460372925, 0.7751..."
4,fashion_mnist_experiment_4__0.1_0.9,0.100,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[2.354529857635498, 2.3601629734039307, 2.3569..."
5,fashion_mnist_experiment_5__1_0.9,1.000,0.9,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[694581.125, 3.625673017744845e+19, 2.99982595..."
6,fashion_mnist_experiment_6__1_0.7,1.000,0.7,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[2.500190258026123, 2.492649555206299, 2.50484..."
7,fashion_mnist_experiment_7__0.01_0.7,0.010,0.7,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[1.1756093502044678, 0.6674687266349792, 0.593..."
8,fashion_mnist_experiment_8__0.001_0.7,0.001,0.7,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[2.2807457447052, 1.620892882347107, 0.9077048..."
9,fashion_mnist_experiment_9__0.005_0.5,0.005,0.5,"{""Step"": [999, 1999, 2999, 3999, 4999, 5999, 6...","[1.9790792465209959, 0.8948003053665161, 0.715..."

In [44]:
df['ID'] = df['Experiment Name'].str.split('__', expand=True)[0]
df['ID'] = df['ID'].str.replace('fashion_mnist_experiment_', '')

df['ID'].astype(int)

0    10
1     1
2     2
3     3
4     4
5     5
6     6
7     7
8     8
9     9
Name: ID, dtype: int64

In [39]:
df_losses = pd.DataFrame(df['Loss Vector'].to_list(), columns=steps)
df_losses.set_index(df['ID']).T

ID,fashion_mnist_experiment_10,fashion_mnist_experiment_1,fashion_mnist_experiment_2,fashion_mnist_experiment_3,fashion_mnist_experiment_4,fashion_mnist_experiment_5,fashion_mnist_experiment_6,fashion_mnist_experiment_7,fashion_mnist_experiment_8,fashion_mnist_experiment_9
999,2.283653,1.781230,1.142389,1.151899,2.354530,6.945811e+05,2.500190,1.175609,2.280746,1.979079
1999,2.127454,0.807675,0.691998,0.873784,2.360163,3.625673e+19,2.492650,0.667469,1.620893,0.894800
2999,1.266696,0.695604,0.594714,0.775100,2.356948,2.999826e+00,2.504843,0.593780,0.907705,0.715526
3999,0.874592,0.606426,0.575674,0.720576,2.361398,2.985374e+00,2.500252,0.557320,0.799478,0.661600
4999,0.801103,0.575231,0.556971,0.730430,2.358875,2.975137e+00,2.497624,0.522928,0.737272,0.617345
5999,0.780064,0.562178,0.526560,0.777657,2.362063,2.931337e+00,2.498943,0.498130,0.678030,0.546121
6999,0.756679,0.518753,0.475073,0.659198,2.356452,2.950568e+00,2.495733,0.501002,0.645386,0.543122
7999,0.689841,0.510753,0.484839,0.733271,2.351617,2.973242e+00,2.501759,0.467036,0.616871,0.507811
8999,0.679204,0.491990,0.485150,0.742674,2.360337,3.005539e+00,2.504469,0.468058,0.613716,0.499790
9999,0.627401,0.470957,0.464938,0.695352,2.359758,3.025568e+00,2.505202,0.435503,0.593945,0.469974
10999,0.635345,0.481770,0.485583,0.807576,2.361112,2.996725e+00,2.494278,0.434296,0.554766,0.441671
11999,0.593593,0.425416,0.451228,0.780502,2.366113,3.013854e+00,2.494060,0.450201,0.556663,0.460627
12999,0.597819,0.443255,0.432670,0.959013,2.359430,3.006247e+00,2.495724,0.441588,0.548877,0.457976
13999,0.601582,0.447701,0.428808,0.830468,2.361907,3.028632e+00,2.504927,0.417989,0.500735,0.456130
14999,0.539334,0.419265,0.438671,0.840145,2.361603,3.013948e+00,2.503967,0.398109,0.522798,0.394805

In [19]:
df_losses

0    [2.2836525440216064, 2.127453565597534, 1.2666...
1    [1.7812299728393557, 0.8076745867729187, 0.695...
2    [1.1423888206481934, 0.691998302936554, 0.5947...
3    [1.151899337768555, 0.8737839460372925, 0.7751...
4    [2.354529857635498, 2.3601629734039307, 2.3569...
5    [694581.125, 3.625673017744845e+19, 2.99982595...
6    [2.500190258026123, 2.492649555206299, 2.50484...
7    [1.1756093502044678, 0.6674687266349792, 0.593...
8    [2.2807457447052, 1.620892882347107, 0.9077048...
9    [1.9790792465209959, 0.8948003053665161, 0.715...
Name: Loss, dtype: object